module.exports = {
  Greek: [[['γεια σου','hello'],['αντίο','goodbye'],['ευχαριστώ','thank you'],['παρακαλώ','please'],['φίλος','friend']],[['ένα','one'],['δύο','two'],['τρία','three'],['τέσσερα','four'],['πέντε','five']],[['κόκκινο','red'],['μπλε','blue'],['πράσινο','green'],['κίτρινο','yellow'],['μαύρο','black']],[['μητέρα','mother'],['πατέρας','father'],['αδελφός','brother'],['αδελφή','sister'],['οικογένεια','family']],[['ψωμί','bread'],['νερό','water'],['γάλα','milk'],['ρύζι','rice'],['μήλο','apple']]],
  Hebrew: [[['שלום','hello'],['להתראות','goodbye'],['תודה','thank you'],['בבקשה','please'],['חבר','friend']],[['אחד','one'],['שתיים','two'],['שלוש','three'],['ארבע','four'],['חמש','five']],[['אדום','red'],['כחול','blue'],['ירוק','green'],['צהוב','yellow'],['שחור','black']],[['אמא','mother'],['אבא','father'],['אח','brother'],['אחות','sister'],['משפחה','family']],[['לחם','bread'],['מים','water'],['חלב','milk'],['אורז','rice'],['תפוח','apple']]],
  Swedish: [[['hej','hello'],['hej då','goodbye'],['tack','thank you'],['snälla','please'],['vän','friend']],[['ett','one'],['två','two'],['tre','three'],['fyra','four'],['fem','five']],[['röd','red'],['blå','blue'],['grön','green'],['gul','yellow'],['svart','black']],[['mamma','mother'],['pappa','father'],['bror','brother'],['syster','sister'],['familj','family']],[['bröd','bread'],['vatten','water'],['mjölk','milk'],['ris','rice'],['äpple','apple']]],
  Norwegian: [[['hei','hello'],['ha det','goodbye'],['takk','thank you'],['vær så snill','please'],['venn','friend']],[['én','one'],['to','two'],['tre','three'],['fire','four'],['fem','five']],[['rød','red'],['blå','blue'],['grønn','green'],['gul','yellow'],['svart','black']],[['mor','mother'],['far','father'],['bror','brother'],['søster','sister'],['familie','family']],[['brød','bread'],['vann','water'],['melk','milk'],['ris','rice'],['eple','apple']]],
  Danish: [[['hej','hello'],['farvel','goodbye'],['tak','thank you'],['venligst','please'],['ven','friend']],[['en','one'],['to','two'],['tre','three'],['fire','four'],['fem','five']],[['rød','red'],['blå','blue'],['grøn','green'],['gul','yellow'],['sort','black']],[['mor','mother'],['far','father'],['bror','brother'],['søster','sister'],['familie','family']],[['brød','bread'],['vand','water'],['mælk','milk'],['ris','rice'],['æble','apple']]],
  Finnish: [[['hei','hello'],['näkemiin','goodbye'],['kiitos','thank you'],['ole hyvä','please'],['ystävä','friend']],[['yksi','one'],['kaksi','two'],['kolme','three'],['neljä','four'],['viisi','five']],[['punainen','red'],['sininen','blue'],['vihreä','green'],['keltainen','yellow'],['musta','black']],[['äiti','mother'],['isä','father'],['veli','brother'],['sisko','sister'],['perhe','family']],[['leipä','bread'],['vesi','water'],['maito','milk'],['riisi','rice'],['omena','apple']]],
  Ukrainian: [[['привіт','hello'],['до побачення','goodbye'],['дякую','thank you'],['будь ласка','please'],['друг','friend']],[['один','one'],['два','two'],['три','three'],['чотири','four'],["п'ять",'five']],[['червоний','red'],['синій','blue'],['зелений','green'],['жовтий','yellow'],['чорний','black']],[['мати','mother'],['батько','father'],['брат','brother'],['сестра','sister'],["сім'я",'family']],[['хліб','bread'],['вода','water'],['молоко','milk'],['рис','rice'],['яблуко','apple']]],
  Czech: [[['ahoj','hello'],['na shledanou','goodbye'],['děkuji','thank you'],['prosím','please'],['přítel','friend']],[['jeden','one'],['dva','two'],['tři','three'],['čtyři','four'],['pět','five']],[['červený','red'],['modrý','blue'],['zelený','green'],['žlutý','yellow'],['černý','black']],[['matka','mother'],['otec','father'],['bratr','brother'],['sestra','sister'],['rodina','family']],[['chléb','bread'],['voda','water'],['mléko','milk'],['rýže','rice'],['jablko','apple']]],
  Hungarian: [[['szia','hello'],['viszlát','goodbye'],['köszönöm','thank you'],['kérem','please'],['barát','friend']],[['egy','one'],['kettő','two'],['három','three'],['négy','four'],['öt','five']],[['piros','red'],['kék','blue'],['zöld','green'],['sárga','yellow'],['fekete','black']],[['anya','mother'],['apa','father'],['fiútestvér','brother'],['lánytestvér','sister'],['család','family']],[['kenyér','bread'],['víz','water'],['tej','milk'],['rizs','rice'],['alma','apple']]],
  Romanian: [[['salut','hello'],['la revedere','goodbye'],['mulțumesc','thank you'],['te rog','please'],['prieten','friend']],[['unu','one'],['doi','two'],['trei','three'],['patru','four'],['cinci','five']],[['roșu','red'],['albastru','blue'],['verde','green'],['galben','yellow'],['negru','black']],[['mamă','mother'],['tată','father'],['frate','brother'],['soră','sister'],['familie','family']],[['pâine','bread'],['apă','water'],['lapte','milk'],['orez','rice'],['măr','apple']]]
};